name = "frufru-dev"
main = "src/index.ts"
compatibility_date = "2024-11-08"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1


[[d1_databases]]
binding = "DB"
database_name = "frufru"
database_id = "652ceb96-b1a4-4c06-9cdc-03e802f36181"

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "furufuru-dev"

# wrangler.toml (wrangler v3.79.0^)
[observability.logs]
enabled = true